[package]
name = "renamer"
version = "0.1.0"
authors = ["Denilson <denilson020898@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11"
structopt = "0.3"